from __future__ import annotations

from agent_videonote.asr.catalog.models import Benchmark, ModelCard


# Curated catalog metadata. This is advisory data, not workflow policy.
# Benchmark values are kept with dataset/source context; do not turn them into
# a universal "accuracy percentage".
BUILTIN_MODELS: tuple[ModelCard, ...] = (
    ModelCard(
        catalog_id="fun-asr-nano-2512",
        name="Fun-ASR-Nano-2512",
        model_id="FunAudioLLM/Fun-ASR-Nano-2512",
        provider_driver="funasr_auto",
        integration_status="supported",
        fit_roles=("primary", "review"),
        languages="中文、英文、日文及多种方言/口音；官方模型卡称覆盖 31 种语言",
        speed="中等偏快",
        quality="中文课程场景优先候选",
        hardware_note="约 0.8B；ModelScope 模型页显示模型文件约 2.15GB。实际显存取决于运行框架、精度和 VAD。",
        strengths=(
            "中文公开集和行业场景表现较强",
            "支持热词，适合课程术语和垂直领域",
            "可通过 FunASR + VAD 获得分段时间轴",
            "当前 Agent-VideoNote 已有直接 Provider",
        ),
        weaknesses=(
            "可靠的 checkpoint 原生逐字时间戳不是它的强项",
            "速度不是 SenseVoice-Small 这类非自回归小模型的级别",
            "不同数据集误差差异较大，不能用单一百分比代表所有课程",
        ),
        capabilities=("hotwords", "segment_timestamp_via_vad", "long_audio", "local"),
        benchmarks=(
            Benchmark(
                dataset="AIShell1",
                metric="WER",
                value=1.80,
                unit="%",
                note="官方 ModelScope 模型卡公开集结果；越低越好。",
                source="https://modelscope.cn/models/FunAudioLLM/Fun-ASR-Nano-2512",
            ),
            Benchmark(
                dataset="WenetSpeech Meeting",
                metric="WER",
                value=6.60,
                unit="%",
                note="官方 ModelScope 模型卡公开集结果；会议远场场景。",
                source="https://modelscope.cn/models/FunAudioLLM/Fun-ASR-Nano-2512",
            ),
            Benchmark(
                dataset="Industry average",
                metric="WER",
                value=16.72,
                unit="%",
                note="官方模型卡多个行业集合的平均值，不能直接等同于你的课程识别率。",
                source="https://modelscope.cn/models/FunAudioLLM/Fun-ASR-Nano-2512",
            ),
        ),
        license_note="商用前仍需按 THIRD_PARTY.md 单独核验代码与模型权重许可证。",
        verified_at="2026-09-28",
        source="https://modelscope.cn/models/FunAudioLLM/Fun-ASR-Nano-2512",
    ),
    ModelCard(
        catalog_id="qwen3-asr-1.7b",
        name="Qwen3-ASR-1.7B",
        model_id="Qwen/Qwen3-ASR-1.7B",
        provider_driver="qwen_asr",
        integration_status="supported",
        fit_roles=("review", "primary"),
        languages="多语言；官方基准覆盖中文、粤语、英语、日语等",
        speed="中等",
        quality="多语言和疑难片段复核优先候选",
        hardware_note="1.7B 级模型；实际显存受 dtype、forced aligner 和上下文长度影响。",
        strengths=(
            "多语言识别能力强",
            "自由上下文能力适合疑难片段复核",
            "语言识别准确率高",
            "当前 Agent-VideoNote 已有直接 Provider",
        ),
        weaknesses=(
            "如果需要时间戳，需额外 forced aligner",
            "作为整片主转写时资源开销通常高于更轻量的 ASR",
            "官方多语言 WER 不能直接转换成单一中文课程识别率",
        ),
        capabilities=("free_context", "hotwords_as_context", "multilingual", "optional_forced_alignment", "local"),
        benchmarks=(
            Benchmark(
                dataset="Fleurs (12 languages)",
                metric="WER",
                value=4.90,
                unit="%",
                note="Qwen 官方仓库多语言基准；不是单独中文 CER。",
                source="https://github.com/QwenLM/Qwen3-ASR/",
            ),
            Benchmark(
                dataset="CommonVoice (13 languages)",
                metric="WER",
                value=9.18,
                unit="%",
                note="Qwen 官方仓库多语言基准。",
                source="https://github.com/QwenLM/Qwen3-ASR/",
            ),
            Benchmark(
                dataset="Language ID average",
                metric="Accuracy",
                value=97.9,
                unit="%",
                note="Qwen 官方仓库语言识别平均准确率，不是转写准确率。",
                source="https://github.com/QwenLM/Qwen3-ASR/",
            ),
        ),
        license_note="商用前仍需按 THIRD_PARTY.md 单独核验代码与模型权重许可证。",
        verified_at="2026-09-28",
        source="https://github.com/QwenLM/Qwen3-ASR/",
    ),
    ModelCard(
        catalog_id="sensevoice-small",
        name="SenseVoice-Small",
        model_id="iic/SenseVoiceSmall",
        provider_driver=None,
        integration_status="catalog_only",
        fit_roles=("primary",),
        languages="多语言语音识别，并可输出语言/情绪/事件标签",
        speed="很快",
        quality="速度优先候选",
        hardware_note="小模型；历史 FunASR GPU 基准记录约 169.6x 实时速度，具体硬件和版本会影响结果。",
        strengths=(
            "速度非常快",
            "适合批量、低成本转写",
            "可同时提供语言/情绪/事件类信息",
        ),
        weaknesses=(
            "当前 Agent-VideoNote 尚未提供专用 Provider",
            "历史 CER 来自归档基准，不代表当前所有版本/课程",
            "如果目标是复杂课程术语，需实测其领域词能力",
        ),
        capabilities=("fast_asr", "language_tags", "emotion_tags", "event_tags"),
        benchmarks=(
            Benchmark(
                dataset="FunASR historical ASR benchmark",
                metric="CER",
                value=7.81,
                unit="%",
                note="FunASR 历史归档基准；同表记录 GPU 约 169.6x 实时速度。",
                source="https://github.com/modelscope/FunASR/blob/main/docs/benchmark/historical_asr.md",
            ),
        ),
        license_note="尚未接入；商用前需单独核验当前模型版本许可证。",
        verified_at="2026-09-28",
        source="https://github.com/modelscope/FunASR/blob/main/docs/benchmark/historical_asr.md",
    ),
    ModelCard(
        catalog_id="whisper-large-v3-turbo",
        name="Whisper Large V3 Turbo",
        model_id="openai/whisper-large-v3-turbo",
        provider_driver=None,
        integration_status="catalog_only",
        fit_roles=("primary", "review"),
        languages="99 种语言",
        speed="快于 Whisper Large V3",
        quality="通用多语言稳健候选",
        hardware_note="Hugging Face 模型页显示仓库约 3.24GB；实际显存取决于框架和精度。",
        strengths=(
            "语言覆盖广",
            "生态成熟",
            "相比 Large V3 大幅减少解码层，速度更快",
        ),
        weaknesses=(
            "当前 Agent-VideoNote 尚未提供 Whisper Provider",
            "中文垂直课程热词能力不是它的核心优势",
            "官方模型卡没有给出一个可与本目录中文模型直接横比的统一中文识别百分比",
        ),
        capabilities=("multilingual", "mature_ecosystem", "local"),
        benchmarks=(),
        license_note="模型卡标注 MIT；真正商用仍需结合所选运行库一起核验。",
        verified_at="2026-09-28",
        source="https://huggingface.co/openai/whisper-large-v3-turbo",
    ),
)
