from __future__ import annotations

from typing import Protocol

from agent_videonote.tasks.models import TaskState


class TaskStore(Protocol):
    def create(self, state: TaskState) -> TaskState: ...
    def load(self, task_id: str) -> TaskState: ...
    def save(self, state: TaskState) -> TaskState: ...
    def exists(self, task_id: str) -> bool: ...
