from __future__ import annotations

from typing import Callable, Protocol

from agent_videonote.tasks.models import TaskState


class TaskStore(Protocol):
    def create(self, state: TaskState) -> TaskState: ...
    def load(self, task_id: str) -> TaskState: ...
    def save(self, state: TaskState) -> TaskState: ...
    def mutate(self, task_id: str, change: Callable[[TaskState], None]) -> TaskState: ...
    def exists(self, task_id: str) -> bool: ...
